name: Run Selenium Tests

on:
  push:
    branches:
      - gitflow
  pull_request:
    branches:
      - gitflow

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Stop hascorepo environment
        run: |
          docker-compose -f docker-compose-hascorepo-development.yml down -v

      - name: Start hascorepo environment
        run: |
          docker-compose -f docker-compose-hascorepo-development.yml up --build -d

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_131.0.6778.69-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_131.0.6778.69-1_amd64.deb

      - name: Download and Install ChromeDriver
        run: |
          DRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.69/linux64/chromedriver-linux64.zip"
    
          curl -L -o chromedriver.zip "$DRIVER_URL"
          
          unzip chromedriver.zip -d /usr/local/bin/
          rm chromedriver.zip

          mv /usr/local/bin/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          chmod +x /usr/local/bin/chromedriver

      - name: Download Selenium standalone jar
        run: |
          curl -L -o selenium-server.jar https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-server/latest/selenium-server-latest.jar
          
      - name: Download JUnit 4.13.2
        run: |
          mkdir -p junit4
          curl -L -o junit4/junit-4.13.2.jar https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
          curl -L -o junit4/hamcrest-core-1.3.jar https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99

      - name: Compile UnitTest.java
        run: |
          javac -cp ".:tests/selenium-java-4.26.0/*:junit4/junit-4.13.2.jar:junit4/hamcrest-core-1.3.jar" tests/UnitTest.java
      
      - name: Wait for hascorepo to be ready
        run: |
          until curl -s http://localhost:8081/ > /dev/null; do
            echo "Waiting for hascorepo environment to start..."
            sleep 5
          done

      - name: Run UnitTest
        run: |
          java -cp ".:tests:tests/selenium-java-4.26.0/*:junit4/junit-4.13.2.jar:junit4/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore tests.UnitTest

      - name: Stop hascorepo environment after tests
        if: always()
        run: |
          docker-compose -f docker-compose-hascorepo-development.yml down -v